name: Тестирование и пробная развертка

on:
  push:
    branches:
      -  develop
    
jobs:
  build:
    runs-on: [ self-hosted, staging ]
    environment: staging
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4
    
      - name: Запись секретов для тестирования в файл .env
        run: |
          cat <<EOF > ${{ github.workspace }}/.env
          APP_ENV=${{ vars.APP_ENV }}
          APP_MODE=${{ vars.APP_MODE }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          BACKEND_HOST=${{ vars.BACKEND_HOST }}
          BACKEND_PORT=${{ vars.BACKEND_PORT }}
          FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}
          FRONTEND_PORT=${{ vars.FRONTEND_PORT }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_API_PORT=${{ vars.NEXT_PUBLIC_API_PORT }}
          EOF
      
      - name: Кешируем .env
        uses: actions/cache@v4
        with:
          path: .env
          key: ${{ runner.os }}-env-${{ github.run_id }}
          
      - name: Сборка докер образа
        run: |
          docker build -f ./backend/Dockerfile -t backend-image ./backend
          
  test:
    needs: build
    runs-on: [ self-hosted, staging ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .env
          key: ${{ runner.os }}-env-${{ github.run_id }}
      
      # - name: Тестирование приложения
      #   run: |
      #     docker run --rm \
      #     --env-file .env \
      #     backend-image \
      #     pytest app/tests -s -v
  
  stage:
    needs: test
    runs-on: [ self-hosted, staging ]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/cache@v4
        with:
          path: .env
          key: ${{ runner.os }}-env-${{ github.run_id }}
          
      - name: Тестовый запуск проекта
        run: |
          docker compose down -v
          docker compose build --no-cache
          COMPOSE_PROJECT_NAME=${{ github.ref_name }} \
          docker compose up -d
