name: Тестирование и пробная развертка

on:
  push:
    branches:
      -  develop
    
jobs:
  build:
    runs-on: [ self-hosted, staging ]
    environment: staging
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4
    
      - name: Запись секретов для тестирования в файл .env
        run: |
          cat <<EOF > .env
          APP_ENV=${{ secrets.APP_ENV }}
          APP_MODE=${{ secrets.APP_MODE }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          BACKEND_HOST=${{ secrets.BACKEND_HOST }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_API_PORT=${{ secrets.NEXT_PUBLIC_API_PORT }}
          EOF
          
      - name: Сборка докер образа
        run: |
          docker build -f ./backend/Dockerfile -t backend-image ./backend
      
      - name: Сохранение .env как артефакта
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: ./.env
          
  test:
    needs: build
    runs-on: [ self-hosted, staging ]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: env-file
      
      - name: Тестирование приложения
        run: |
          docker run --rm \
          --env-file .env \
          backend-image \
          pytest app/tests -s -v
  
  stage:
    needs: test
    runs-on: [ self-hosted, staging ]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: env-file
          
      - name: Тестовый запуск проекта
        run: |
          COMPOSE_PROJECT_NAME=${{ github.ref_name }} \
          docker compose up --build --force-recreate -d
