name: Развертывание проекта в продакшн

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, production ]
    environment: production
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4

      - name: Запись секретов продакшена в файл .env.frontend
        run: |
          mkdir ${{ github.workspace }}/config
          
          cat <<EOF > ${{ github.workspace }}/config/.env.frontend
          APP_MODE=${{ vars.APP_MODE }}
          NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_API_PORT=${{ vars.NEXT_PUBLIC_API_PORT }}
          EOF

          cat <<EOF > ${{ github.workspace }}/config/.env.backend
          APP_ENV=${{ vars.APP_ENV }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          BACKEND_HOST=${{ vars.BACKEND_HOST }}
          BACKEND_PORT=${{ vars.BACKEND_PORT }}
          FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}
          FRONTEND_PORT=${{ vars.FRONTEND_PORT }}
          EOF

          cat <<EOF > ${{ github.workspace }}/config/.env.pg
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          EOF

      - name: Запуск проекта
        run: |
          COMPOSE_PROJECT_NAME=${{ github.ref_name }} \
          docker compose -f ${{ github.workspace }}/compose.yml up -d --build --force-recreate
