name: Развертывание проекта в продакшн

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, production ]
    environment: production
    steps:
      - name: Синхронизация проекта с репозиторием
        uses: actions/checkout@v4

      - name: Запись секретов продакшена в файл .env
        run: |
          cat <<EOF > ${{ github.workspace }}/.env
          APP_ENV=${{ vars.APP_ENV }}
          APP_MODE=${{ vars.APP_MODE }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          BACKEND_HOST=${{ vars.BACKEND_HOST }}
          BACKEND_PORT=${{ vars.BACKEND_PORT }}
          FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}
          FRONTEND_PORT=${{ vars.FRONTEND_PORT }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_API_PORT=${{ vars.NEXT_PUBLIC_API_PORT }}
          EOF

      - name: Запуск проекта
        run: |
          docker compose -f ${{ github.workspace }}/compose.yml down -v
          docker compose -f ${{ github.workspace }}/compose.yml build --no-cache
          COMPOSE_PROJECT_NAME=${{ github.ref_name }} \
          docker compose -f ${{ github.workspace }}/compose.yml up -d
